# Generated by Django 4.2.6 on 2023-10-15 22:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('birthdate', models.DateField()),
                ('category', models.CharField(choices=[('Adult', 'Adult'), ('Teen', 'Teen'), ('Sunday School', 'Sunday School'), ('Visitor', 'Visitor')], max_length=15)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
